### ISSUE TITLE
就是想问一下有没有纯小白也能懂从环境搭建开始的教程

### ISSUE THREAD

**Issue by good951753** [hang333/HbookerAppNovelDownloader#17]
就是想问一下有没有纯小白也能懂从环境搭建开始的教程

**Comment by lixiangwuxian** [comment]
具体哪个部分的环境不会搭建呢

**Comment by good951753** [comment]
> 具体哪个部分的环境不会搭建呢
> python在微软商店里直接就能下载，依赖的库用`pip install <名称>`就可以安装；
> 运行方式也写的很清楚了。

从就需求环境pycryptodome或pycrypto就卡住了，还有依赖的库用`pip installl <pycryptodome>是这样加的吗？

**Comment by lixiangwuxian** [comment]
是的

**Comment by good951753** [comment]
> 是的
> 或者`python -m pip install <名称>`也可

谢谢∩_∩
