### ISSUE TITLE
登录的接口好像不能用了

### ISSUE THREAD

**Issue by litchiar** [hang333/HbookerAppNovelDownloader#20]

**Comment by litchiar** [comment]
输入指令l 账号 密码后会显示账号或密码错误

**Comment by shuai2931806756** [comment]
login 账户 密码 无限显示错误。但登app没问题，要咋解决呀？

**Comment by w-e-w** [comment]
已經有解決方式
但登入流程會變得麻煩

**Comment by litchiar** [comment]
的确我试了下可以直接通过login_token登录，但方法相当繁琐

**Comment by shuai2931806756** [comment]
> 
啊，大佬，细说下。。。

**Comment by shuai2931806756** [comment]
> 的确我试了下可以直接通过login_token登录，但方法相当繁琐

这个login_token 如何获取呀？

**Comment by litchiar** [comment]
安卓抓包

**Comment by Elaina-Alex** [comment]
> 

可以尝试抓包或者使用本地缓存token

**Comment by shuai2931806756** [comment]
> 可以尝试抓包或者使用本地缓存token

我通过网页版登陆来获取token可以不？之后需要怎么继续呀？

**Comment by shuai2931806756** [comment]
> 目前已更新使用token的登入方式 提供兩種匯入token方法 指令 i 詳見readme

出现了{'code': '200100', 'tip': '登录状态过期，请重新登录'}。。 这个要咋解决呀。。。  瑟瑟发抖。。

**Comment by EliasMercer** [comment]
> 

大佬请问下面这个哪个是token那个是account
success":1,"gt":"32位16进制","challenge":"32位16进制","new_captcha":true

**Comment by w-e-w** [comment]
都不是，完全錯了，你這是geetest用的東西
你要找的是以下這兩個
login_token=<32hex>
account=书客1234567890

**Comment by EliasMercer** [comment]
> 都不是，完全錯了，你這是geetest用的東西 你要找的像是以下這兩個 login_token=<32hex> account=书客1234567890

请问方便加一下qq吗，还有一些别的想问一下

**Comment by EliasMercer** [comment]
> 都不是，完全错了，你这是geetest用的东西 你要找的像是以下这两个 login_token=<32hex> account=书客1234567890

请问方便加一下qq吗，还有一些别的想问一下，我的qq1148967896

**Comment by EliasMercer** [comment]
> 都不是，完全错了，你这是geetest用的东西 你要找的像是以下这两个 login_token=<32hex> account=书客1234567890

搞好了，谢谢

**Comment by EliasMercer** [comment]
> 都不是，完全錯了，你這是geetest用的東西 你要找的像是以下這兩個 login_token=<32hex> account=书客1234567890

大佬，麻烦看看，今天又登不上去了

**Comment by shiki-su** [comment]
> 都不是，完全錯了，你這是geetest用的東西 你要找的像是以下這兩個 login_token=<32hex> account=书客1234567890

大佬，又用不了了，麻烦看看

**Comment by shiki-su** [comment]
> 都不是，完全錯了，你這是geetest用的東西 你要找的像是以下這兩個 login_token=<32hex> account=书客1234567890

大佬，代码用不了了，麻烦看看

**Comment by w-e-w** [comment]
@shiki-su 剛才測試並沒有發現問題

**Comment by shiki-su** [comment]
> @shiki-su 剛才測試並沒有發現問題

删了重下了一遍发现又能用了，抱歉打扰了

**Comment by kuruuru** [comment]
> > 目前已更新使用token的登入方式 提供兩種匯入token方法 指令 i 詳見readme
> 
> 出现了{'code': '200100', 'tip': '登录状态过期，请重新登录'}。。 这个要咋解决呀。。。 瑟瑟发抖。。

不好意思在数月后又打开了这个issue，遇到了同样的bug。

登录时：
`accout：'书客id'`
`login_token：'32hex' `
login_token的获取是用chrome在刺猬猫官网进行登录时抓包，在doLogin项下，找到同名的32位token输入此处。
同时发现该token的expires时间还有接近7天。

返回：
`Token已汇入`
`add device_token': 'ciweimao_`
`未登入，请先登入`
`签到失败，特殊原因，请手动处理:`
`{'code': '200100', 'tip': '登录状态过期，请重新登录'}`

请问下作者这种情况应该怎么处理？
谢谢。

**Comment by w-e-w** [comment]
> > > 目前已更新使用token的登入方式 提供兩種匯入token方法 指令 i 詳見readme
> > 
> > 出现了{'code': '200100', 'tip': '登录状态过期，请重新登录'}。。 这个要咋解决呀。。。 瑟瑟发抖。。
> 
> 不好意思在数月后又打开了这个issue，遇到了同样的bug。
> 
> 登录时：
> `accout：'书客id'`
> `login_token：'32hex' `
> login_token的获取是用chrome在刺猬猫官网进行登录时抓包，在doLogin项下，找到同名的32位token输入此处。
> 同时发现该token的expires时间还有接近7天。
> 
> 返回：
> `Token已汇入`
> `add device_token': 'ciweimao_`
> `未登入，请先登入`
> `签到失败，特殊原因，请手动处理:`
> `{'code': '200100', 'tip': '登录状态过期，请重新登录'}`
> 
> 请问下作者这种情况应该怎么处理？
> 谢谢。

@kuruuru 

用錯token了
是要用Android手機app的token
網站的是網站的
手機的app的是手機app的
雖然都是token，但卻是不同東西的token
