### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by nadaofuxitele** [hang333/HbookerAppNovelDownloader#26]
纯小白，完全没有运行过任何一套电脑代码的经验，从来没碰过cmd，来到github社区完全是恼火刺猬猫封书，想要提前为冷圈小众同人小说在互联网留下备份记录（圈子小很冷门连盗版都没有，但就是无缘无故被封），已经通过熬夜一整晚勉强给电脑安装了python和系统变量运行cmd的run.py，在电脑上安装了adb工具，已经到达了xml提取这一阶段，可是不论如何手段提取出来的data似乎都是1 kb大小的文件，网上也找不到解决办法，请求作者能有一个详细一些的答案，或是提供另一个渠道的详细流程，因为各种原因手机没有root。。抓包的话完全不懂。。。

**Comment by trunkovo** [comment]
（抓包方案）下一个叫 AndroidHttpCapture 的app（Github就有），按照app内提示安装证书、设置代理（“HTTPS抓包”和“全局抓包”）；打开一下刺猬猫app，随便点开一本书；切回去打开“查看请求包”，搜索“hbooker”，随便点开一个，在“request postdata”栏下找对应的参数，没有就换一个。希望这已经是足够详细的教程…… @nadaofuxitele

**Comment by w-e-w** [comment]
另一個方式是在PC上安裝android模擬器 類似bluestacks 
大部分的模擬器都有root功能啟用

**Comment by w-e-w** [comment]
com.kuangxiangciweimao.novel_preferences.xml 的檔案大小因該約2~3KB

**Comment by w-e-w** [comment]
如果沒有root的話是無法使用root的方式的

**Comment by w-e-w** [comment]
至於非root android 的方式
我基本上readme中的這段 因該是已經非常清楚了
```
備份data/data/com.kuangxiangciweimao.novel
adb backup -f data -noapk com.kuangxiangciweimao.novel
使用https://github.com/nelenkov/android-backup-extractor 將data轉成tar
java -jar .\abe.jar unpack data data.tar
再用7z或其他壓縮軟件解壓所
"C:\Program Files\7-Zip\7z.exe" x .\data.tar
後獲取檔案xml
"apps\com.kuangxiangciweimao.novel\sp\com.kuangxiangciweimao.novel_preferences.xml"
```

**Comment by w-e-w** [comment]
抓包的方式trunkovo也提供了
具體怎麼做 我懶所以沒寫 自己往上找

**Comment by nadaofuxitele** [comment]
> 另一个类似bluestacks的方式是在PC上安装android的方式 启用了root功能 @nadaofuxitele

我输入的指令是adb backup -f D:\data -noapk com.kuangxiangciweimao.novel
产生了一个1kb大小也就是47字节的文件，网上查询后说是无用文件，不知道我的指令是否正确，我一直使用的·阿·非root方法。。

**Comment by nadaofuxitele** [comment]
> （抓抓安装包）下一个叫AndroidHttpCapture的app（Gub有HTTPS），通过app提示包提示安装证书和“内抓安装包”）；打开“抓抓包”；打开刺刺猫app，顺便点开一个搜索；回头打开查看请求包”，“hbooker”，顺便打开一个，在“request postdata”栏下找一个参数，没有就换一个。这已经是的教程了……@nadaofuxitele

非常感谢，正在努力，但每次抓包欢乐书客都连不上网，正在想办法解决

**Comment by w-e-w** [comment]
`adb backup -f D:\data -noapk com.kuangxiangciweimao.novel`
???
哪來的`D:\`
是
`adb backup -f data -noapk com.kuangxiangciweimao.novel`

**Comment by w-e-w** [comment]
另外執行後手機上因該會有提示確認是否執行備份

**Comment by nadaofuxitele** [comment]
> `adb backup -f D:\data -noapk com.kuangxiangciweimao.novel` ??? 来哪`D:\` 是 `adb backup -f data -noapk com.kuangxiangciweimao.novel`

感谢作者。。。但完全找不到备份后的文件位置，在date前面加d:\不是备份到指定文件夹吗

**Comment by w-e-w** [comment]
確實 `D:\data` 是指定路徑 這是指定絕對路徑 到D:\data
但條件是你的電腦中有 D碟 且可以被使用
並不是所有電腦都有D碟 像是是我的就沒有D
如果不指定`D:\`則他會使用相對路徑，也就是當前目錄下建立檔案
而我寫的步驟是全部都是使用相對路徑的
也就是說 你架上了`D:\`後 導致之後所有也要做相應的改變
所以這是在增加可能出錯的變數

**Comment by nadaofuxitele** [comment]
> 



> 當前目錄



> 確實 `D:\data` 是指定路徑 這是指定絕對路徑 到D:\data 但條件是你的電腦中有 D碟 且可以被使用 但並不是所有電腦都有D碟 (像是是我的就沒有D) 如果不指定`D:\`則它會使用相對路徑，也就是當前目錄下建立檔案 而我寫的步驟是全部都是使用相對路徑的 也就是說 你架上了`D:\`後 導致之後所有也要做相應的改變 所以這是在增加可能出錯的變數

我想知道的就是这个默认目录的具体位置.....显示备份已经完成，是C:\Windows\system32>吗?

**Comment by nadaofuxitele** [comment]
> 相對路徑

C:\Windows\SysWOW64里面确实有一个data文件，但还是47字节1kb大小，想知道是不是和书客版本有关系，不知道书客有没有禁止allowBackup。。

**Comment by w-e-w** [comment]
目前工作目錄
![wd](https://user-images.githubusercontent.com/40751091/185387021-de501eda-943f-4bdc-86fe-60d04c443aa4.png)
更多資訊 搜尋 "工作目錄" 或 "Working directory"

**Comment by w-e-w** [comment]
> C:\Windows\SysWOW64里面确实有一个data文件
不可能 別亂動系統文件

**Comment by nadaofuxitele** [comment]
> 目前工作目錄 ![wd](https://user-images.githubusercontent.com/40751091/185387021-de501eda-943f-4bdc-86fe-60d04c443aa4.png) 更多資訊 搜尋 "工作目錄" 或 "Working directory"
![Screenshot 2022-08-18 200854](https://user-images.githubusercontent.com/110630854/185391342-f7593291-f9a9-4d01-8acf-c75f1973997e.png)
![Screenshot 2022-08-18 201154](https://user-images.githubusercontent.com/110630854/185391746-fb0e181a-93e9-4bf8-b5b0-21b3517c0e73.png)
您看，我是在当前目录执行的这条指令，但得到的仍然是一个1kb文件，如果我上图的指令正确得到的文件，那要么是adb有问题，要么是hbook禁止adb。。。。。

**Comment by nadaofuxitele** [comment]
> > C:\Windows\SysWOW64里面确实有一个data文件
> 
> 不可能 別亂動系統文件
![Screenshot 2022-08-18 200624](https://user-images.githubusercontent.com/110630854/185393993-a77c6a20-8fea-47b5-9d60-90bf12ed88d7.png)
您看，我是在工作目录里通过完整复制您的代码输入的指令，唔，但得到的文件仍然是这个
![Screenshot 2022-08-18 202406](https://user-images.githubusercontent.com/110630854/185394405-6a6e79ca-330e-499c-adee-65fd4d208115.png)
手机上没有设置备份密码，选择备份后过了几秒提示备份成功，然后在目录里出现了这个1kb文件。。。。如果指令和cmd的目录都没有错，想知道是否是adb的问题还是书客禁止adb backup

**Comment by w-e-w** [comment]
基本上建議學如何抓包
或使用android模擬器 啟用root功能

**Comment by nadaofuxitele** [comment]
> 基本上建議學如何抓包 或使用android模擬器 啟用root功能

唔，万幸的是有一部安卓4.4.4版本的超远古三星，正在尝试给他root.....实在不行就只能抓包或用模拟器.....

**Comment by w-e-w** [comment]
太舊的版本android可能有其他問題 4.4都10多年了

**Comment by w-e-w** [comment]
我個人從安全信信的角度上是對使用抓包軟體有疑慮的
> 這就是我沒寫出抓包實際過程的一個原因
本質上抓包是做中間人攻擊
如果使用的抓包軟體本身有問題，這代表你的通訊可能會被洩漏，可能導致帳號被盜取等狀況
所以如果要使用抓包 必須要確認能信任你所使用的工具 而且請盡量了解抓包到底是在做什麼 後再進行

**Comment by nadaofuxitele** [comment]
> ，我是在工作目录里通过完整复制您的代码输入的指



> （抓包方案）下一个叫 AndroidHttpCapture 的app（Github就有），按照app内提示安装证书、设置代理（“HTTPS抓包”和“全局抓包”）；打开一下刺猬猫app，随便点开一本书；切回去打开“查看请求包”，搜索“hbooker”，随便点开一个，在“request postdata”栏下找对应的参数，没有就换一个。希望这已经是足够详细的教程…… @nadaofuxitele

非常感谢，已经通过夜神模拟器配合框架成功抓包登录啦

**Comment by w-e-w** [comment]
@nadaofuxitele 如果有空的話你可以寫一個“你都能也能看得懂的教學”
這樣下個人也看得懂

**Comment by w-e-w** [comment]
可以，有勞了

**Comment by nadaofuxitele** [comment]
简单抓包的过程，下载一个夜神模拟器，确认通过模拟器右上角设置-基础是否打开了root，先用模拟器的浏览器下载刺猬猫app，用模拟器自带的浏览器进入https://github.com/JZ-Darkal/AndroidHttpCapture，下载操作手册上方的的demo.apk程序并安装，进入https://forum.xda-developers.com/t/official-xposed-for-lollipop-marshmallow-nougat-oreo-v90-beta3-2018-01-29.3034811/ 下载下方的XposedInstaller_3.1.5.apk文件安装，同时下载https://github.com/Fuzion24/JustTrustMe/releases/tag/v.2下的JustTrustMe.apk进行安装。
安装XposedInstaller_3.1.5后进入XposedInstaller，安装软件内的框架，会提示重启，模拟器画面会固定一定时间，重启后打开软件XposedInstaller点击左上角打开模块，勾选justtrustme。
打开AndroidHttpCapture程序，点开左上角的设置，点击设置系统代理，长按已链接的wifi会跳出一个修改网络的选项，将代理改为手动，将服务器主机名改为127.0.0.1，端口改为8888，选择保存后不要退出程序，用右下角程序选择返回桌面。
登入刺猬猫app账户，随便打开一本书，返回AndroidHttpCapture程序，点击左上角选择查看请求包，查找hbooker，点击进入数据详情，查看request postdata栏目下是否有account，后面是书客某某某某某的数字，记下下方的login token内的32位字母数字。
在电脑上下载https://www.python.org/downloads/里适合的phtony软件，解压c盘或其他位置，进入解压的文件夹，复制或记住名称上方框内的文件路径后进入下方的scripts文件夹，同样记住路径，如D:\pythone和D:\pythone\Scripts，右键点击我的电脑或找到设置打开系统，找到下方的关于，进入后选择右边的高级系统设置，选择高级，打开环境变量，选择系统变量中的path，选择编辑，进入后点击新建，在框内输入你的路径，然后再新建另一个，输入scripts文件夹的路径。
win键+R键打开运行，打开cmd，输入pip install requests等待下载完成。
打开cmd，复制黏贴或打上你下载的刺猬猫提取器文件夹路径，在后面加上\run.py，进入目录，前面的缩写都是后面的对应指令，在cmd上打入英文字母l，打上数字2，先填入你的书客xxxxxx，然后填上login_token里获取的那一长串字符，登陆成功。

**Comment by nadaofuxitele** [comment]
> 可以，有勞了

请问下载完后的文件在哪个文件夹，是工作目录吗

**Comment by nadaofuxitele** [comment]
> @nadaofuxitele 如果有空的話你可以寫一個“你都能也能看得懂的教學” 這樣下個人也看得懂

求问，下载时有时候会显示Get Error Retry: HTTPSConnectionPool，这是怎么回事呢

**Comment by w-e-w** [comment]
@nadaofuxitele 非常抱歉
之前回覆問題時在手機上操作錯誤 以為是在回覆問題 但卻變成編輯問題

現在重新回復問題
Q
> 请问下载完后的小说文件在哪个文件夹，是工作目录吗
A
預設是在工作目錄下的hbooker子資料夾中 但會根據hbookerappnoveldownloader.json保存的改變

Q
> 求问，下载时有时候会显示Get Error Retry: HTTPSConnectionPool(host='app.hbooker.com', port=443):，这是怎么回事呢
A

連線過程出錯 重新嘗試

理解常網頁加在失敗，重新嘗試加載
若連續出現10次失敗的話會 停止下載 終止程序 

為何會出現失敗？ 可能原因太多，無法得知
從“你家網路不”好到“伺服器覺得你是駭客所以把你的連線斷了” 都有可能

建議
嘗試間段下載 可能當前時間他們的伺服器較繁忙

另外由於無法得知伺服器有沒有檢測異常帳號/活動等機制 所以無法證實
但果你是在大量下載書籍後突然開始出現 有可能是帳號或IP被標記為"可疑活動" 所以被斷線
不排除帳號被封的風險 建議不要大量連續下載書籍
