### ISSUE TITLE
请问这个目前还能用么？

### ISSUE THREAD

**Issue by elaiio** [hang333/HbookerAppNovelDownloader#32]
每次登入之后都会显示”登陆状态过期2，请重新登入“

**Comment by elaiio** [comment]
![屏幕截图 2023-09-20 153814](https://github.com/hang333/HbookerAppNovelDownloader/assets/145540327/abbf3609-5b7b-4e8e-877e-548670369e5f)

**Comment by elaiio** [comment]
![Uploading 屏幕截图 2023-09-20 153814.png…]()

**Comment by elaiio** [comment]
![屏幕截图 2023-09-20 153814](https://github.com/hang333/HbookerAppNovelDownloader/assets/145540327/4afc8e9a-9bc9-458f-87b6-5edadc0b4dfa)

**Comment by elaiio** [comment]
啊，解决了！

**Comment by 1026833619** [comment]
> 啊，解决了！

同问题，请问大概如何解决的，仅思路就好
