### ISSUE TITLE
在這討論下 關於關於版本封號檢測

### ISSUE THREAD

**Issue by w-e-w** [hang333/HbookerAppNovelDownloader#8]
可能寫得有點亂，先抱歉。

可以透過訪問
https://app.hbooker.com/setting/get_version (網頁瀏覽器也可以) 獲得 :
`{'code': '100000', 'data': {'is_force_update': '0', 'android_down_url': 'http://www.ciweimao.com/setting/download/common', 'android_version': '2.6.019', 'android_update_content': '更新内容：修复部分手机闪退的bug', 'ios_version': '2.0.17', 'ios_update_content': '', 'ios_down_url': 'http://www.ciweimao.com/setting/download/common'}}`

獲取 android_version":"`2.6.019`"  
但目前最新版本是 `2.7.039`
版號不同讓我產生疑慮

注 我沒自己花時間去解析官方APP 所以下為猜測
`簡要: 我猜測版本號對他們不太重要`

測試
剛剛嘗試刷新書架 將 `'app_version': ''` (無)
伺服器回覆是
 `Error: {'code': '200005', 'tip': '版本过低，请更新软件版本(绑定手机号可以防止账号丢失)'}`  

(我不敢嘗試太多次，也不敢亂嘗試不同的版本號 怕他們會紀錄統計帳號登入使用的版本 不想造成可疑紀錄)

大意就是 基本上如果版本不夠就是直接不讓訪問
有可能是判定是個簡單的 大於XX版本就可以通過 但就是怕他們會統計
也有可能需要特定的版本號

不管如何，就算用舊版的，我不覺得他們會因為這個原因封號，畢竟很多人懶，不更新

目前不清楚當 `is_force_update': '1'` 時會有什麼狀況，不清楚會不會強制更才能使用的狀況

如果要的話 是可以根據回傳的數字來設定版本號參數 但這真的好嗎?
首先 我不確定這個版號跟APP版號是否完全相同，(因為現在看得的是2個不投的版號)，不知道用抓取得合不合適，雖然大概綠沒問題

再來假設麼個版本突然大改(雖然不可太能(他們的伺服器貌似N年沒變的感覺))，改變大到腳本有嚴重不適用，(舊版本會出現`code: 200005` 的狀況)，強制使用者更新
這時候如果自動把版本號改成 新版號 腳本強制執行，有概率這個大改版後會改變調用方式，導致嚴重的錯誤以及可疑調用，反而提高封號機率

如果當在APP收到更通知 手動修訂版本號也沒有太費事
可以改成版本號從config讀取，這樣要改也方便

有什麼想法嗎?

**Comment by w-e-w** [comment]
如果要說可疑調用
正常人是不會透過只會透共書架，不會偷過ID找書的
所以要說 下載不再說價中的書本深夜算是可疑訪問

**Comment by w-e-w** [comment]
有部分我不太清楚
伺服器是怎麼裝置的
目前如果用現在的腳本 用不同的token登入時(登入2次)會把另外token作廢，像是類似同裝上登入2次舊的得被自動登出這樣
但與此同時手機APP登入，甚至另外大佬寫的Cirno卻登入時可以跟這個腳本同登入
不清楚伺服器是如何判斷的
我唯一猜測是與`HbookerAPI.HttpUtil`中的`headers = {'User-Agent': 'Android'}`
但嘗試將`Android`改成`Android9`隨然可以正常登入(甚至可以用同一個token) 之後用`Android`登入但還token過期

**Comment by w-e-w** [comment]
剛剛在手機瀏覽器上嘗試https://app.hbooker.com/setting/get_version  

{"code":"100000","data":{"is_force_update":"1","android_down_url":"http:\/\/www.hbooker.com\/setting\/download?channel=qzsj","android_version":"1.5.539","android_update_content":"\u65e7\u7248\u672c\u5373\u5c06\u8fc7\u671f\uff0c\u8bf7\u60a8\u53ca\u65f6\u66f4\u65b0\uff1b\u66f4\u65b0\u5185\u5bb9\uff1a1,\u4e66\u5ba2\u53f2\u4e0a\u6700\u7a33\u5b9a\u7248\u672c;2,\u542c\u4e66\u8bf7\u4f7f\u7528\u523a\u732c\u732bapp\u7533\u8bf7\u5185\u6d4b\u83b7\u53d6","ios_version":"2.0.17","ios_update_content":"","ios_down_url":"http:\/\/www.ciweimao.com\/setting\/download\/common"}}

在這裡得到的是1.5.539 
更詭異了 ，不知道該怎麼想

**Comment by hang333** [comment]
刚刚发现通过 https://www.ciweimao.com/index/app 的 "apk 下载" 选项的话, 会 redirect 至
https://c1.kuangxiangit.com/custom/download/2.0.112/Novel-common-release_27039_jiagu_sign-PCdownloadC.apk
其中 27039 便是最新的安卓版本号

**Comment by w-e-w** [comment]
這個我知道 之前下載APK注意到過 下載APK黨名有包含版本字串 
https://www.ciweimao.com/setting/download 之後會被轉到 上面那串
如果要的話是可以提取 27039 轉成 但前提是版本號保持 x.y.zzz的格式
版本號 有可能突然變成 2.10.123 之類的 這實在很難自動去判斷，甚至有時候多了個" a" ex 2.9.123a 總之很隨意
所以這樣的話可能還是寫成 有可以自動抓取版本號功能 然後根據使用者判斷確認後再更改 這樣的方式

再來遇到點問題 https://www.ciweimao.com/setting/download 這個連結後面的伺服器有某種裝置認證，因該是某中確認是瀏覽器而不是爬蟲的機制存在，因該是利用headers的某項參數，如果不通過就返回ERROR 403，不會進行redirect到APK位置
總之目前無法取得APK URL

建議先Pull了現在的版本 只少現在的可以從config改版本號 (加入的檢查版本功能是手動執行的，所以不會有影響)

有空時再花點時間在嘗試 https://www.ciweimao.com/setting/download 的方式上

或許目前依據https://app.hbooker.com/setting/get_version就可以用了 ，需要等下個版本的APP出後觀察返回字串的變化判斷

**Comment by hang333** [comment]
请问有没有私底下的联系方式或是 PGP Public Key（直接在 issue 中交流） 呢？
我的 PGP Key 是
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEYHBMMBYJKwYBBAHaRw8BAQdArc31T1LN5AWbfvouFaF5GYFogHleyCn+XMYz
M7SPl8e0IkpvbmF0aGFuIEdvaCA8aGFuZzMzM0BoYW5nMzMzLm1vZT6IlgQTFggA
PhYhBGTNywmu+cDG5gMY8BxaLukFeMvOBQJgcEwwAhsDBQkDwewQBQsJCAcCBhUK
CQgLAgQWAgMBAh4BAheAAAoJEBxaLukFeMvOdGMA+wSp48+xLJI+vA6FWLYIDdiC
9xh52hDZ/xjDIAoaGv43AQDMw/EW2ELuZUOYYK63T3dDV1Q1+csLx+m3YgMOs0FU
CLg4BGBwTDASCisGAQQBl1UBBQEBB0DApzt6vBn32zXVjrRUt6kw/fshdQ7lQa03
oMXANbFNJQMBCAeIfgQYFggAJhYhBGTNywmu+cDG5gMY8BxaLukFeMvOBQJgcEww
AhsMBQkDwewQAAoJEBxaLukFeMvOY38A/iYCP+u8VBG/zTWqQrCPmMt8TJbuAJ0N
aBJVdaN0oNrZAQDocyWnbzC0CSZkIHqyYIPG31LreAJ8JzOQ4/z0MsgvCg==
=Ltw+
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by w-e-w** [comment]
你有嘗試用你的public key加密過嗎? 我這邊出錯了
可能key被github吞掉幾個字符?

我這剛臨時生成public key，用這個加密你的聯繫方式吧。
email twitter qq 或別的應該都可
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG C# v1.6.1.0

mQENBGBwWz0BCADE/PjrB+av13izrj2MmT1Dcdi9JGmcpScJdL7ZLc4WPMLHP5nz
fSL+tAJ2h0dUtHDtUqV4ACwOUicd3h+O16eZfSP+7ovtY8OIRg/AjvMUwlVgArWf
dxLc/8o1xXnkGN7nt/Bg8ZEWxqGgBd7YfD7QgZ4RmMOux1MnGHt2vHWx/vwGWvf8
76Fw/o+HF5sftk+ibq6+U5Y+ZxXk0Jt3GtKFA6pKyAivZ1aLVxL55gV465KEJ8ej
CvPC90uSFrPuk48lUFxi5LuQvQCy0EFz91PldkITrMPI1Bi4Y3dk3yhaPWYU53Ol
lw2czPdoq6G+hlPWLZ+cJYHVyh8k/bQmft4PABEBAAG0BzF1c2VwZ3CJARwEEAEC
AAYFAmBwWz0ACgkQ+vhPmKfv+d3flQf/TSwETd/Jdxg95rY5/nqkXmB8a/Ldx4Lk
+DEOO56iBAJ/wW+ZUzXWEzEU/Dhs+IpU/gcwhNwnrXqAofWWtgq3Lpvecles46gE
2DtAK1eor44u9tlJD5UT/YO8JnnyDVwokXbIe8Wo6RIVJQax53+bbgn10zz7WtWJ
kqbhb/YPngVHN+kkbNvBQXQFIbcEkyW2ULYnY7/FVh8Q3J6OSU9bpCW/dBNQZe1A
zVK/LpnAFaI3bi4qJi0r5NizuNLZ9HqtiGGXRu2cMRH24WWQ32l7xId4Gl7lHOJi
pr/+UHBcNMGfkSiV1TgUMe6tKMN3STQAWEnjeUkHf/YIcr800BqisQ==
=BYYS
-----END PGP PUBLIC KEY BLOCK-----
```
(加密測試成功)

**Comment by hang333** [comment]
> 你有嘗試用你的public key加密過嗎? 我這邊出錯了
> 可能key被github吞掉幾個字符?
> 
> 我這剛臨時生成public key，用這個加密你的聯繫方式吧。
> email twitter qq 或別的應該都可
> 
> ```
> -----BEGIN PGP PUBLIC KEY BLOCK-----
> Version: BCPG C# v1.6.1.0
> 
> mQENBGBwWz0BCADE/PjrB+av13izrj2MmT1Dcdi9JGmcpScJdL7ZLc4WPMLHP5nz
> fSL+tAJ2h0dUtHDtUqV4ACwOUicd3h+O16eZfSP+7ovtY8OIRg/AjvMUwlVgArWf
> dxLc/8o1xXnkGN7nt/Bg8ZEWxqGgBd7YfD7QgZ4RmMOux1MnGHt2vHWx/vwGWvf8
> 76Fw/o+HF5sftk+ibq6+U5Y+ZxXk0Jt3GtKFA6pKyAivZ1aLVxL55gV465KEJ8ej
> CvPC90uSFrPuk48lUFxi5LuQvQCy0EFz91PldkITrMPI1Bi4Y3dk3yhaPWYU53Ol
> lw2czPdoq6G+hlPWLZ+cJYHVyh8k/bQmft4PABEBAAG0BzF1c2VwZ3CJARwEEAEC
> AAYFAmBwWz0ACgkQ+vhPmKfv+d3flQf/TSwETd/Jdxg95rY5/nqkXmB8a/Ldx4Lk
> +DEOO56iBAJ/wW+ZUzXWEzEU/Dhs+IpU/gcwhNwnrXqAofWWtgq3Lpvecles46gE
> 2DtAK1eor44u9tlJD5UT/YO8JnnyDVwokXbIe8Wo6RIVJQax53+bbgn10zz7WtWJ
> kqbhb/YPngVHN+kkbNvBQXQFIbcEkyW2ULYnY7/FVh8Q3J6OSU9bpCW/dBNQZe1A
> zVK/LpnAFaI3bi4qJi0r5NizuNLZ9HqtiGGXRu2cMRH24WWQ32l7xId4Gl7lHOJi
> pr/+UHBcNMGfkSiV1TgUMe6tKMN3STQAWEnjeUkHf/YIcr800BqisQ==
> =BYYS
> -----END PGP PUBLIC KEY BLOCK-----
> ```
> 
> (加密測試成功)

-----BEGIN PGP MESSAGE-----

hQEMA/r4T5in7/ndAQf/Qp0dRUe5JV3wTz4Dm6aMsWBVGtxgSu2QCivkvIaolWiG
/mxb+zmqJdBeutdmEmjiM8x/2itM2+Mzz/i9xhdFYDVmkzXva4jabwZO2K1sAf9r
fge8WyiS1pY+lqFVF+y+DaZ/AVmGuebr8nYsaWovcyS4llEA08/cBZmpnw2gvUbh
fRvL7WNpC4k30ZUwmFGWs3gvuJzTwykHdZynmzuQaJ6Vqj+dJksksPUD397+JA2A
DQVtR9LDemCJq4JgW/6MJ9oABwukwHTSXmo9W5JKp6FxUoxBcbJtNJHj91Vz4yZP
PJjlbwGzXF+RlnXZzpkT5LXtqpgUPJdN4zWIXEkMz9LAywGv1o9nRwPk5NcK8Gh2
LNNAA0J9WU8xNThryvTYuF88DH9ZMY0zXx2aMI0vYa57rUXpmRLbb6nArG0hSRBy
LxNOGIvj86wkdhspIDWd4iqQKG9p6M35JIsL0bjmP5WCiqcL0j5CYgiMUCLM4UQo
b8/ywryD9IlzGy+U7hwoCaJH+wJBT1rCVka/y4/SxSo2BFUrv+faFj0gpae5Z/6R
2tLaEw8UaSQFgGvc8ybyhjS7HaURZaGKKlgdup4v0qHSg8D80K4G4nMAHTibOM8l
hx8k4Hxht/8SAXSQxEkbFZ9AxihU6012AmKNanA+mGKCMYDcrNtPGyHYU57saK/z
aZA4knSBGN+2HQJ/S8j6QKQwYwUNvtJkHfGSqiVbys36EJeTuAqlrHS78GYouv24
yrvMwiQ2SrfHSTN6cxvOhKIjlRr09Kc7Akg8bxOa+uyRwf91FusyrC4/sqil5s6D
9enHFlHwGRNcdTiHHF/jed4tBDnzmvxH0XxEsOYMusFAE+7OEIhMnNLZ3noM
=xtxT
-----END PGP MESSAGE-----
